Import

In [362]:
import pandas as pd
import numpy as np

Load file

In [363]:
text1 ='''Tracy loves writing about data science.'''

In [364]:
text2 = '''Tracy loves writing for medium publications.'''

In [365]:
text3 = '''Tracy loves studying Python programming.'''

In [366]:
text4 = '''Tracy loves entering Kaggle competitions.'''

In [367]:
text5 = '''Tracy loves making YouTube videos.'''

In [368]:
text6 = '''Tracy loves getting new subscribers.'''

Corpus

In [369]:
corpus = [text1, text2, text3, text4, text5, text6]
corpus

['Tracy loves writing about data science.',
 'Tracy loves writing for medium publications.',
 'Tracy loves studying Python programming.',
 'Tracy loves entering Kaggle competitions.',
 'Tracy loves making YouTube videos.',
 'Tracy loves getting new subscribers.']

Count Vectorizer

In [370]:
from sklearn.feature_extraction.text import CountVectorizer

count_vec = CountVectorizer()

matrix = count_vec.fit_transform(corpus)
pd.DataFrame(matrix.toarray(), index=['doc1','doc2', 'doc3', 'doc4', 'doc5', 'doc6'],columns=count_vec.get_feature_names())

about  competitions  data  entering  ...  tracy  videos  writing  youtube
doc1      1             0     1         0  ...      1       0        1        0
doc2      0             0     0         0  ...      1       0        1        0
doc3      0             0     0         0  ...      1       0        0        0
doc4      0             1     0         1  ...      1       0        0        0
doc5      0             0     0         0  ...      1       1        0        1
doc6      0             0     0         0  ...      1       0        0        0

[6 rows x 21 columns]

Tfidf Transformer

In [371]:
from sklearn.feature_extraction.text import TfidfTransformer 

tf_transformer = TfidfTransformer().fit(matrix)
word_count_vec_tf = tf_transformer.transform(matrix)
word_count_vec_tf.shape

(6, 21)

In [372]:
df0 = pd.DataFrame(word_count_vec_tf.toarray(),columns=count_vec.get_feature_names(),index=['doc1','doc2', 'doc3', 'doc4', 'doc5', 'doc6'])
df0

about  competitions      data  ...    videos  writing   youtube
doc1  0.495894      0.000000  0.495894  ...  0.000000  0.40664  0.000000
doc2  0.000000      0.000000  0.000000  ...  0.000000  0.40664  0.000000
doc3  0.000000      0.000000  0.000000  ...  0.000000  0.00000  0.000000
doc4  0.000000      0.542798  0.000000  ...  0.000000  0.00000  0.000000
doc5  0.000000      0.000000  0.000000  ...  0.542798  0.00000  0.542798
doc6  0.000000      0.000000  0.000000  ...  0.000000  0.00000  0.000000

[6 rows x 21 columns]

Sum Values

In [373]:
df0_sum = df1.sum(axis=1)
df0_sum

doc1    1.121124
doc2    1.271173
doc3    1.140682
doc4    1.140682
doc5    0.038709
doc6    0.975254
dtype: float64

Cosine similarity

In [374]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(df0[0:1], df0)

array([[1.        , 0.26226788, 0.10607812, 0.10607812, 0.10607812,
        0.10607812]])

Hashing
Vectorizer

In [375]:
#see:- https://kavita-ganesan.com/hashingvectorizer-vs-countvectorizer/#.YR-sw4hKg2w

from sklearn.feature_extraction.text import HashingVectorizer

vectorizer = HashingVectorizer(n_features=21)

X = vectorizer.fit_transform(corpus)
X.shape

(6, 21)

In [376]:
matrix = pd.DataFrame(X.toarray(), index=['doc1','doc2', 'doc3', 'doc4', 'doc5', 'doc6'])
matrix

0    1    2         3    4   ...        16        17        18   19   20
doc1  0.000000  0.0  0.0  0.000000  0.0  ...  0.353553  0.000000  0.000000  0.0  0.0
doc2  0.000000  0.0  0.0  0.000000  0.0  ...  0.408248  0.000000  0.000000  0.0  0.0
doc3  0.000000  0.0  0.0  0.000000  0.0  ...  0.447214  0.447214  0.000000  0.0  0.0
doc4  0.000000  0.0  0.0  0.000000  0.0  ...  0.447214 -0.447214  0.000000  0.0  0.0
doc5  0.000000  0.0  0.0 -0.447214  0.0  ...  0.447214  0.000000  0.000000  0.0  0.0
doc6 -0.447214  0.0  0.0  0.000000  0.0  ...  0.447214  0.000000  0.447214  0.0  0.0

[6 rows x 21 columns]

In [377]:
matrix.shape

(6, 21)

Tfidf Transformer

In [378]:
from sklearn.feature_extraction.text import TfidfTransformer 

tf_transformer = TfidfTransformer().fit(matrix)
word_count_vec_tf = tf_transformer.transform(matrix)
word_count_vec_tf.shape

(6, 21)

In [379]:
df1 = pd.DataFrame(word_count_vec_tf.toarray(),index=['doc1','doc2', 'doc3', 'doc4', 'doc5', 'doc6'])
df1

0    1    2         3    4   ...        16        17        18   19   20
doc1  0.000000  0.0  0.0  0.000000  0.0  ...  0.196875  0.000000  0.000000  0.0  0.0
doc2  0.000000  0.0  0.0  0.000000  0.0  ...  0.240337  0.000000  0.000000  0.0  0.0
doc3  0.000000  0.0  0.0  0.000000  0.0  ...  0.268221  0.495485  0.000000  0.0  0.0
doc4  0.000000  0.0  0.0  0.000000  0.0  ...  0.268221 -0.495485  0.000000  0.0  0.0
doc5  0.000000  0.0  0.0 -0.571054  0.0  ...  0.253491  0.000000  0.000000  0.0  0.0
doc6 -0.571054  0.0  0.0  0.000000  0.0  ...  0.253491  0.000000  0.571054  0.0  0.0

[6 rows x 21 columns]

Sum values

In [380]:
df1_sum = df1.sum(axis=1)
df1_sum

doc1    1.121124
doc2    1.271173
doc3    1.140682
doc4    1.140682
doc5    0.038709
doc6    0.975254
dtype: float64

Cosine similarity

In [381]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(df1[0:1], df1)

array([[1.        , 0.41756776, 0.10561219, 0.10561219, 0.09981198,
        0.09981198]])

TfidfVectorizer

In [382]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
trsfm=vectorizer.fit_transform(corpus)
df2 = pd.DataFrame(trsfm.toarray(),columns=vectorizer.get_feature_names(),index=['doc1','doc2', 'doc3', 'doc4', 'doc5', 'doc6'])
df2

about  competitions      data  ...    videos  writing   youtube
doc1  0.495894      0.000000  0.495894  ...  0.000000  0.40664  0.000000
doc2  0.000000      0.000000  0.000000  ...  0.000000  0.40664  0.000000
doc3  0.000000      0.000000  0.000000  ...  0.000000  0.00000  0.000000
doc4  0.000000      0.542798  0.000000  ...  0.000000  0.00000  0.000000
doc5  0.000000      0.000000  0.000000  ...  0.542798  0.00000  0.542798
doc6  0.000000      0.000000  0.000000  ...  0.000000  0.00000  0.000000

[6 rows x 21 columns]

In [383]:
df2.shape

(6, 21)

Sum values

In [384]:
df2_sum = df2.sum(axis=1)
df2_sum

doc1    2.334575
doc2    2.334575
doc3    2.110289
doc4    2.110289
doc5    2.110289
doc6    2.110289
dtype: float64

Cosine similarity

In [385]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(df2[0:1], df2)

array([[1.        , 0.26226788, 0.10607812, 0.10607812, 0.10607812,
        0.10607812]])