Import

In [64]:
import pandas as pd
import numpy as np

Load file

In [65]:
text1 ='''Tracy loves writing about data science.'''

In [66]:
text2 = '''Tracy loves writing for medium publications.'''

In [67]:
text3 = '''Tracy loves studying Python programming.'''

In [68]:
text4 = '''Tracy loves entering Kaggle competitions.'''

In [69]:
text5 = '''Tracy loves making YouTube videos.'''

In [70]:
text6 = '''Tracy loves getting new subscribers.'''

Corpus

In [71]:
corpus = [text1, text2, text3, text4, text5, text6]
corpus

['Tracy loves writing about data science.',
 'Tracy loves writing for medium publications.',
 'Tracy loves studying Python programming.',
 'Tracy loves entering Kaggle competitions.',
 'Tracy loves making YouTube videos.',
 'Tracy loves getting new subscribers.']

CounterVectorizer

In [72]:

from sklearn.feature_extraction.text import CountVectorizer

count_vec = CountVectorizer()

word_count_vec = count_vec.fit_transform(corpus)
word_count_vec.shape

(6, 21)

Print vocabulary

In [73]:
print(count_vec.get_feature_names())

['about', 'competitions', 'data', 'entering', 'for', 'getting', 'kaggle', 'loves', 'making', 'medium', 'new', 'programming', 'publications', 'python', 'science', 'studying', 'subscribers', 'tracy', 'videos', 'writing', 'youtube']


In [74]:
print("Vocabulary: ", count_vec.vocabulary_)

Vocabulary:  {'tracy': 17, 'loves': 7, 'writing': 19, 'about': 0, 'data': 2, 'science': 14, 'for': 4, 'medium': 9, 'publications': 12, 'studying': 15, 'python': 13, 'programming': 11, 'entering': 3, 'kaggle': 6, 'competitions': 1, 'making': 8, 'youtube': 20, 'videos': 18, 'getting': 5, 'new': 10, 'subscribers': 16}


In [75]:
print(word_count_vec.toarray())

[[1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0]
 [0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0]]


Encode document

In [76]:
vector = count_vec.transform(corpus)
print(vector)

  (0, 0)	1
  (0, 2)	1
  (0, 7)	1
  (0, 14)	1
  (0, 17)	1
  (0, 19)	1
  (1, 4)	1
  (1, 7)	1
  (1, 9)	1
  (1, 12)	1
  (1, 17)	1
  (1, 19)	1
  (2, 7)	1
  (2, 11)	1
  (2, 13)	1
  (2, 15)	1
  (2, 17)	1
  (3, 1)	1
  (3, 3)	1
  (3, 6)	1
  (3, 7)	1
  (3, 17)	1
  (4, 7)	1
  (4, 8)	1
  (4, 17)	1
  (4, 18)	1
  (4, 20)	1
  (5, 5)	1
  (5, 7)	1
  (5, 10)	1
  (5, 16)	1
  (5, 17)	1


In [77]:
print("Encoded Document is:")
print(vector.toarray())

Encoded Document is:
[[1 0 1 0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 1 0 1 0 0 1 0 0 0 0 1 0 1 0]
 [0 0 0 0 0 0 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0]
 [0 1 0 1 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 1 1 0 1]
 [0 0 0 0 0 1 0 1 0 0 1 0 0 0 0 0 1 1 0 0 0]]


Count words

In [78]:

# Use the content column instead of our single text variable
matrix = count_vec.fit_transform(corpus)
counts = pd.DataFrame(matrix.toarray(), index=['doc1','doc2', 'doc3', 'doc4', 'doc5', 'doc6'],columns=count_vec.get_feature_names())
counts

about  competitions  data  entering  ...  tracy  videos  writing  youtube
doc1      1             0     1         0  ...      1       0        1        0
doc2      0             0     0         0  ...      1       0        1        0
doc3      0             0     0         0  ...      1       0        0        0
doc4      0             1     0         1  ...      1       0        0        0
doc5      0             0     0         0  ...      1       1        0        1
doc6      0             0     0         0  ...      1       0        0        0

[6 rows x 21 columns]

Add total column

In [79]:
counts.loc['Total',:]= counts.sum(axis=0)
counts

about  competitions  data  entering  ...  tracy  videos  writing  youtube
doc1     1.0           0.0   1.0       0.0  ...    1.0     0.0      1.0      0.0
doc2     0.0           0.0   0.0       0.0  ...    1.0     0.0      1.0      0.0
doc3     0.0           0.0   0.0       0.0  ...    1.0     0.0      0.0      0.0
doc4     0.0           1.0   0.0       1.0  ...    1.0     0.0      0.0      0.0
doc5     0.0           0.0   0.0       0.0  ...    1.0     1.0      0.0      1.0
doc6     0.0           0.0   0.0       0.0  ...    1.0     0.0      0.0      0.0
Total    1.0           1.0   1.0       1.0  ...    6.0     1.0      2.0      1.0

[7 rows x 21 columns]