Import

In [1016]:
import pandas as pd
import numpy as np

Load file

In [1017]:
text1 ='''Tracy loves writing about data science.'''

In [1018]:
text2 = '''Tracy loves writing for medium publications.'''

In [1019]:
text3 = '''Tracy loves studying Python programming.'''

In [1020]:
text4 = '''Tracy loves entering Kaggle competitions.'''

Corpus

In [1021]:
corpus = [text1, text2, text3, text4]
corpus

['Tracy loves writing about data science.',
 'Tracy loves writing for medium publications.',
 'Tracy loves studying Python programming.',
 'Tracy loves entering Kaggle competitions.']

CounterVectorizer

In [1022]:

from sklearn.feature_extraction.text import CountVectorizer

count_vec = CountVectorizer()

word_count_vec = count_vec.fit_transform(corpus)
word_count_vec.shape

(4, 15)

Print vocabulary

In [1023]:
print(count_vec.get_feature_names())

['about', 'competitions', 'data', 'entering', 'for', 'kaggle', 'loves', 'medium', 'programming', 'publications', 'python', 'science', 'studying', 'tracy', 'writing']


In [1024]:
print("Vocabulary: ", count_vec.vocabulary_)

Vocabulary:  {'tracy': 13, 'loves': 6, 'writing': 14, 'about': 0, 'data': 2, 'science': 11, 'for': 4, 'medium': 7, 'publications': 9, 'studying': 12, 'python': 10, 'programming': 8, 'entering': 3, 'kaggle': 5, 'competitions': 1}


In [1025]:
print(word_count_vec.toarray())

[[1 0 1 0 0 0 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 0 1 1 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0 1 1 0]
 [0 1 0 1 0 1 1 0 0 0 0 0 0 1 0]]


Encode document

In [1026]:
vector = count_vec.transform(corpus)
print(vector)

  (0, 0)	1
  (0, 2)	1
  (0, 6)	1
  (0, 11)	1
  (0, 13)	1
  (0, 14)	1
  (1, 4)	1
  (1, 6)	1
  (1, 7)	1
  (1, 9)	1
  (1, 13)	1
  (1, 14)	1
  (2, 6)	1
  (2, 8)	1
  (2, 10)	1
  (2, 12)	1
  (2, 13)	1
  (3, 1)	1
  (3, 3)	1
  (3, 5)	1
  (3, 6)	1
  (3, 13)	1


In [1027]:
print("Encoded Document is:")
print(vector.toarray())

Encoded Document is:
[[1 0 1 0 0 0 1 0 0 0 0 1 0 1 1]
 [0 0 0 0 1 0 1 1 0 1 0 0 0 1 1]
 [0 0 0 0 0 0 1 0 1 0 1 0 1 1 0]
 [0 1 0 1 0 1 1 0 0 0 0 0 0 1 0]]


In [1028]:

# Use the content column instead of our single text variable
matrix = count_vec.fit_transform(corpus)
counts = pd.DataFrame(matrix.toarray(), index=['doc1','doc2', 'doc3', 'doc4'],columns=count_vec.get_feature_names())
counts

about  competitions  data  entering  ...  science  studying  tracy  writing
doc1      1             0     1         0  ...        1         0      1        1
doc2      0             0     0         0  ...        0         0      1        1
doc3      0             0     0         0  ...        0         1      1        0
doc4      0             1     0         1  ...        0         0      1        0

[4 rows x 15 columns]

TfidfTransformer

In [1029]:
from sklearn.feature_extraction.text import TfidfTransformer 

tf_transformer = TfidfTransformer(use_idf=False).fit(matrix)
word_count_vec_tf = tf_transformer.transform(matrix)
word_count_vec_tf.shape

(4, 15)

In [1030]:
df1 = pd.DataFrame(word_count_vec_tf.toarray(),columns=count_vec.get_feature_names(),index=['doc1','doc2', 'doc3', 'doc4'])
df1

about  competitions      data  ...  studying     tracy   writing
doc1  0.408248      0.000000  0.408248  ...  0.000000  0.408248  0.408248
doc2  0.000000      0.000000  0.000000  ...  0.000000  0.408248  0.408248
doc3  0.000000      0.000000  0.000000  ...  0.447214  0.447214  0.000000
doc4  0.000000      0.447214  0.000000  ...  0.000000  0.447214  0.000000

[4 rows x 15 columns]

In [1031]:
df1.shape

(4, 15)

In [1032]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 4 entries, doc1 to doc4
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   about         4 non-null      float64
 1   competitions  4 non-null      float64
 2   data          4 non-null      float64
 3   entering      4 non-null      float64
 4   for           4 non-null      float64
 5   kaggle        4 non-null      float64
 6   loves         4 non-null      float64
 7   medium        4 non-null      float64
 8   programming   4 non-null      float64
 9   publications  4 non-null      float64
 10  python        4 non-null      float64
 11  science       4 non-null      float64
 12  studying      4 non-null      float64
 13  tracy         4 non-null      float64
 14  writing       4 non-null      float64
dtypes: float64(15)
memory usage: 512.0+ bytes


Cosine similarity - sklearn

In [1033]:
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity(df1[0:1], df1)

array([[1.        , 0.5       , 0.36514837, 0.36514837]])